import Link from 'next/link';
import './globals.scss';
import { Inter } from 'next/font/google';
import Navbar from './components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ess">
      <body className={inter.className}>
        <header className="top-0 sticky  ">
          <Navbar></Navbar>
        </header>
        {children}
        <footer>
          <ul className="social-media-links">
            <li>
              <Link href="#">WhatsApp</Link>
            </li>
            <li>
              <Link href="#">Instagram</Link>
            </li>
            <li>
              <Link href="#">Facebook</Link>
            </li>
            <li>
              <Link href="#">YouTube</Link>
            </li>
          </ul>
          <p>Club Mariano Moreno de Castelar</p>
          <p>triskeltechcreactivos@gmail.com</p>
        </footer>
      </body>
    </html>
  );
}
